services:
  web:
    build: docker/php-apache
    image: wp_tech_blog_web_image
    container_name: wp-tech-blog-web
    volumes:
      - ./app:/var/www/html/
      - ./docker/php-apache/apache/mods-enabled/auth_digest.load:/etc/apache2/mods-enabled/auth_digest.load
      - ./docker/php-apache/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/php-apache/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-apache/php/conf.d/custom-prod.ini:/usr/local/etc/php/conf.d/custom-prod.ini
      - ./docker/php-apache/apache/password:/etc/apache2/password
    ports:
      - 80:80

networks:
  default:
    name: wp-tech-blog.internal
